import type { LevelConfig } from './types'

export const LEVELS: LevelConfig[] = [
  {
    id: 1,
    name: 'First Flight',
    subtitle: 'Draw your first vector',
    shipStart: { x: 80, y: 220 },
    target: { x: 360, y: 220 },
    targetRadius: 40,
    asteroids: [],
    fuelBudget: 0,
    par: 1,
    showGrid: true,
    showComponents: false,
    hint: 'Drag from the ship rightward to draw a vector. Make it reach the gold ring!',
  },
  {
    id: 2,
    name: 'Diagonal',
    subtitle: 'Vectors have direction AND magnitude',
    shipStart: { x: 80, y: 340 },
    target: { x: 340, y: 80 },
    targetRadius: 36,
    asteroids: [],
    fuelBudget: 0,
    par: 1,
    showGrid: true,
    showComponents: true,
    hint: 'Drag diagonally! See how the dashed lines show the x and y components.',
  },
  {
    id: 3,
    name: 'Detour',
    subtitle: 'Go around the obstacle',
    shipStart: { x: 60, y: 220 },
    target: { x: 380, y: 220 },
    targetRadius: 32,
    asteroids: [{ cx: 220, cy: 220, r: 50 }],
    fuelBudget: 0,
    par: 2,
    showGrid: true,
    showComponents: true,
    hint: 'One vector won\'t work — the asteroid is in the way! Use two vectors to go around it.',
  },
  {
    id: 4,
    name: 'Tight Squeeze',
    subtitle: 'Thread the needle',
    shipStart: { x: 60, y: 220 },
    target: { x: 380, y: 220 },
    targetRadius: 30,
    asteroids: [
      { cx: 200, cy: 150, r: 42 },
      { cx: 200, cy: 290, r: 42 },
    ],
    fuelBudget: 500,
    par: 3,
    showGrid: false,
    showComponents: true,
    hint: 'Navigate through the gap between the two asteroids. Watch your fuel!',
  },
  {
    id: 5,
    name: 'Fuel Crunch',
    subtitle: 'Find the efficient path',
    shipStart: { x: 80, y: 340 },
    target: { x: 360, y: 80 },
    targetRadius: 32,
    asteroids: [],
    fuelBudget: 380,
    par: 1,
    showGrid: true,
    showComponents: true,
    hint: 'Tight fuel budget! Going diagonally is more efficient than right-then-up. Can you do it in one vector?',
  },
  {
    id: 6,
    name: 'Asteroid Field',
    subtitle: 'Navigate the debris',
    shipStart: { x: 50, y: 380 },
    target: { x: 390, y: 50 },
    targetRadius: 30,
    asteroids: [
      { cx: 140, cy: 300, r: 35 },
      { cx: 240, cy: 200, r: 40 },
      { cx: 320, cy: 130, r: 30 },
      { cx: 170, cy: 160, r: 25 },
    ],
    fuelBudget: 600,
    par: 4,
    showGrid: false,
    showComponents: true,
    hint: 'Weave through the asteroid field. Plan your route carefully — each vector counts!',
  },
  {
    id: 7,
    name: 'Spiral Path',
    subtitle: 'The scenic route',
    shipStart: { x: 220, y: 400 },
    target: { x: 220, y: 60 },
    targetRadius: 28,
    asteroids: [
      { cx: 220, cy: 230, r: 55 },
      { cx: 120, cy: 140, r: 30 },
      { cx: 340, cy: 310, r: 28 },
    ],
    fuelBudget: 650,
    par: 3,
    showGrid: false,
    showComponents: false,
    hint: 'A massive asteroid blocks the direct path. Find a way around — but conserve fuel!',
  },
  {
    id: 8,
    name: 'Gauntlet',
    subtitle: 'The final challenge',
    shipStart: { x: 40, y: 400 },
    target: { x: 400, y: 40 },
    targetRadius: 28,
    asteroids: [
      { cx: 120, cy: 320, r: 30 },
      { cx: 200, cy: 260, r: 35 },
      { cx: 280, cy: 200, r: 30 },
      { cx: 350, cy: 130, r: 28 },
      { cx: 160, cy: 170, r: 22 },
      { cx: 320, cy: 310, r: 25 },
    ],
    fuelBudget: 700,
    par: 5,
    showGrid: false,
    showComponents: false,
    hint: 'Six asteroids. One target. Many vectors. Good luck, pilot!',
  },
]
