import type { LevelConfig } from './types'

export const LEVELS: LevelConfig[] = [
  {
    id: 1,
    name: 'Gentle Curve',
    subtitle: 'Use a gravity well to bend your path',
    shipStart: { x: 60, y: 220 },
    target: { x: 380, y: 120 },
    targetRadius: 36,
    asteroids: [],
    wellPar: 1,
    showGrid: true,
    hint: 'Draw a launch vector from the ship, then tap to place a gravity well. The well bends the ship\'s path toward it!',
  },
  {
    id: 2,
    name: 'Around the Rock',
    subtitle: 'Curve around an asteroid',
    shipStart: { x: 60, y: 220 },
    target: { x: 380, y: 220 },
    targetRadius: 32,
    asteroids: [{ cx: 220, cy: 220, r: 45 }],
    wellPar: 1,
    showGrid: true,
    hint: 'An asteroid blocks the direct path! Place a well above or below to curve around it.',
  },
  {
    id: 3,
    name: 'Slingshot',
    subtitle: 'A strong well can make a U-turn',
    shipStart: { x: 200, y: 380 },
    target: { x: 200, y: 60 },
    targetRadius: 32,
    asteroids: [
      { cx: 200, cy: 220, r: 40 },
    ],
    wellPar: 1,
    showGrid: false,
    hint: 'The target is directly above, but a massive asteroid blocks you. Launch sideways and use a strong well to slingshot back!',
  },
  {
    id: 4,
    name: 'Double Bend',
    subtitle: 'Navigate an S-curve with two wells',
    shipStart: { x: 50, y: 350 },
    target: { x: 390, y: 80 },
    targetRadius: 30,
    asteroids: [
      { cx: 170, cy: 230, r: 38 },
      { cx: 300, cy: 180, r: 38 },
    ],
    wellPar: 2,
    showGrid: false,
    hint: 'Two asteroids form a chicane. Place wells on alternating sides to weave through.',
  },
  {
    id: 5,
    name: 'The Corridor',
    subtitle: 'Thread through a narrow gap',
    shipStart: { x: 60, y: 350 },
    target: { x: 380, y: 100 },
    targetRadius: 28,
    asteroids: [
      { cx: 200, cy: 180, r: 35 },
      { cx: 200, cy: 290, r: 35 },
      { cx: 330, cy: 200, r: 28 },
    ],
    wellPar: 2,
    showGrid: false,
    hint: 'A tight gap between asteroids. Precise well placement is key!',
  },
  {
    id: 6,
    name: 'Orbital',
    subtitle: 'Curve nearly 180° around the cluster',
    shipStart: { x: 60, y: 100 },
    target: { x: 60, y: 340 },
    targetRadius: 30,
    asteroids: [
      { cx: 140, cy: 220, r: 35 },
      { cx: 220, cy: 160, r: 30 },
      { cx: 220, cy: 280, r: 30 },
    ],
    wellPar: 2,
    showGrid: false,
    hint: 'The target is almost directly below you, but asteroids block the short route. Use wells to orbit around!',
  },
  {
    id: 7,
    name: 'Ricochet',
    subtitle: 'A complex curved path with three wells',
    shipStart: { x: 40, y: 400 },
    target: { x: 400, y: 40 },
    targetRadius: 28,
    asteroids: [
      { cx: 150, cy: 310, r: 32 },
      { cx: 260, cy: 200, r: 35 },
      { cx: 340, cy: 120, r: 28 },
      { cx: 120, cy: 160, r: 25 },
    ],
    wellPar: 3,
    showGrid: false,
    hint: 'Multiple obstacles require a complex curve. Place three wells to thread the needle!',
  },
  {
    id: 8,
    name: 'The Gauntlet',
    subtitle: 'Dense field — master the gravity wells',
    shipStart: { x: 40, y: 400 },
    target: { x: 400, y: 40 },
    targetRadius: 28,
    asteroids: [
      { cx: 120, cy: 320, r: 28 },
      { cx: 200, cy: 260, r: 32 },
      { cx: 280, cy: 200, r: 28 },
      { cx: 350, cy: 130, r: 26 },
      { cx: 160, cy: 160, r: 22 },
      { cx: 320, cy: 300, r: 24 },
    ],
    wellPar: 3,
    showGrid: false,
    hint: 'Six asteroids. Full gauntlet. Careful well placement is everything!',
  },
]
